server {
    listen 8081;
    server_name localhost;

    root /var/www/static-site;
    index index.html;

    # Custom access log
    access_log /var/log/nginx/custom_access.log custom_format;

    # Custom error log
    error_log /var/log/nginx/custom_error.log warn;

    location / {
        try_files $uri $uri/ =404;
    }
}