server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;

    root /var/www/static-site;
    index index.html;
}

server {
    listen 8081;
    server_name localhost;
    return 301 https://$host$request_uri;   # force HTTP → HTTPS
}




