server {
    listen 8081;
    server_name localhost;

    root /var/www/static-site;
    index index.html;

    location / {
        add_header X-Debug-Host $host;
        add_header X-Debug-IP $remote_addr;
        add_header X-Debug-URI $request_uri;
        return 200 "Host: $host | IP: $remote_addr | URI: $request_uri\n";
    }
}